// <auto-generated />
namespace SportscardSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AuditInfowereaddedandsetuped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditInfowereaddedandsetuped));
        
        string IMigrationMetadata.Id
        {
            get { return "201803192239339_AuditInfo were added and setuped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
